[workspace]
members = ["./crates/aviutl2-sys", "./examples/webp-input", "crates/aviutl2", "examples/ffmpeg-output"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
aviutl2-sys = { path = "./crates/aviutl2-sys" }
aviutl2 = { path = "./crates/aviutl2" }
