[package]
name = "ffmpeg-output"
version.workspace = true
edition.workspace = true



[lib]
name = "rusty_ffmpeg_output"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.98"
aviutl2.workspace = true
ez-ffmpeg = { version = "0.5.1", features = ["static"] }
# ez-ffmpeg = { version = "0.5.1" }
ffmpeg-next = "7.1.0"
ffmpeg-sys-next = "7.1.3"
