[package]
name = "ffmpeg-output"
version.workspace = true
edition.workspace = true

[lib]
name = "rusty_ffmpeg_output"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.98"
aviutl2.workspace = true
process_path = "0.1.4"
ureq = "3.0.12"
zip-extract = "0.4.0"
