[package]
name = "aviutl2"
version.workspace = true
edition.workspace = true

[features]
default = ["input", "output"]
input = []
output = []

[dependencies]
anyhow = "1.0.98"
aviutl2-sys.workspace = true
duplicate = "2.0.0"
native-dialog = "0.9.0"
num-rational = "0.4.2"
