[package]
name = "aviutl2"
version.workspace = true
edition.workspace = true

[features]
default = ["input", "output"]
input = []
output = []

[dependencies]
anyhow = "1.0.98"
aviutl2-sys.workspace = true
num-rational = "0.4.2"
