[package]
name = "example-image-rs-input"
version = "0.1.0"
edition = "2024"

[lib]
name = "rusty_images"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.98"
aviutl2.workspace = true
image = "0.25.6"
